import "@/styles/globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { ThirdwebWrapper } from "@/components/ThirdwebWrapper";
import { ThemeWrapper } from "@/components/ThemeWrapper";
import { PropsWithChildren } from "react";
import { Navbar } from "@/components/Navbar";
import { Sidebar } from "@/components/Sidebar";
import { Bottombar } from "@/components/Bottombar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} container py-6 flex flex-col min-h-screen gap-4`}
      >
        <ThemeWrapper
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ThirdwebWrapper>
            <header>
              <Navbar />
            </header>
            <main className="flex flex-1 gap-4">
              <Sidebar />
              {children}
            </main>
            <footer>
              <Bottombar />
            </footer>
          </ThirdwebWrapper>
        </ThemeWrapper>
      </body>
    </html>
  );
}
