import { Navbar } from "@/components/Navbar";
import { ThemeWrapper } from "@/components/ThemeWrapper";
import { ThirdwebWrapper } from "@/components/ThirdwebWrapper";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased min-h-screen flex flex-col`}
      >
        <ThemeWrapper
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ThirdwebWrapper>
            <header>
              <Navbar />
            </header>
            <main className="flex flex-col flex-1">{children}</main>
          </ThirdwebWrapper>
        </ThemeWrapper>
      </body>
    </html>
  );
}
